CREATE TABLE `tb_auth_aqtw_10000000` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增唯一ID',
  `scope` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '授权范围,目前只有0,活动粒度授权',
  `actId` varchar(64) NOT NULL COMMENT '活动id',
  `uid` varchar(64) NOT NULL COMMENT '渠道侧用户ID',
  `openid` varchar(64) NOT NULL COMMENT '游戏账号openid/gopenid',
  `sArea` varchar(8) NOT NULL DEFAULT '' COMMENT '大区',
  `sPlatId` varchar(8) NOT NULL DEFAULT '' COMMENT '平台ID',
  `sPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '小区ID',
  `sRoleId` varchar(64) NOT NULL DEFAULT '' COMMENT '角色ID',
  `srcPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '出生服小区ID，用于转区',
  `sAmsNewRoleId` varchar(80) NOT NULL DEFAULT '' COMMENT '唯一角色ID，用于转区',
  `sExtend` varchar(512) NOT NULL DEFAULT '' COMMENT '绑定的扩展信息，JSON格式',
  `data` text COMMENT '绑定数据，JSON 格式',
  `bindStatus` tinyint(3) unsigned NOT NULL COMMENT '绑定状态：1-已绑定，2-已解绑',
  `bindTime` datetime NOT NULL COMMENT '绑定时间',
  `bindSerial` char(50) NOT NULL COMMENT '绑定时的流水号',
  `bindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '绑定次数',
  `bindFrom` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定来源',
  `bindPhone` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定的手机号',
  `unbindTime` datetime DEFAULT NULL COMMENT '解绑时间',
  `unbindSerial` char(50) NOT NULL DEFAULT '' COMMENT '解绑时的流水号',
  `unbindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '解绑次数',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `game_channel_openid` (`openid`) COMMENT '索引：业务-渠道-openid',
  KEY `channel_uid` (`uid`) COMMENT '索引：渠道-uid'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='渠道用户和游戏角色的绑定关系表';
CREATE TABLE `tb_auth_aqtw_10011001` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增唯一ID',
  `scope` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '授权范围,目前只有0,活动粒度授权',
  `actId` varchar(64) NOT NULL COMMENT '活动id',
  `uid` varchar(64) NOT NULL COMMENT '渠道侧用户ID',
  `openid` varchar(64) NOT NULL COMMENT '游戏账号openid/gopenid',
  `sArea` varchar(8) NOT NULL DEFAULT '' COMMENT '大区',
  `sPlatId` varchar(8) NOT NULL DEFAULT '' COMMENT '平台ID',
  `sPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '小区ID',
  `sRoleId` varchar(64) NOT NULL DEFAULT '' COMMENT '角色ID',
  `srcPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '出生服小区ID，用于转区',
  `sAmsNewRoleId` varchar(80) NOT NULL DEFAULT '' COMMENT '唯一角色ID，用于转区',
  `sExtend` varchar(512) NOT NULL DEFAULT '' COMMENT '绑定的扩展信息，JSON格式',
  `data` text COMMENT '绑定数据，JSON 格式',
  `bindStatus` tinyint(3) unsigned NOT NULL COMMENT '绑定状态：1-已绑定，2-已解绑',
  `bindTime` datetime NOT NULL COMMENT '绑定时间',
  `bindSerial` char(50) NOT NULL COMMENT '绑定时的流水号',
  `bindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '绑定次数',
  `bindFrom` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定来源',
  `bindPhone` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定的手机号',
  `unbindTime` datetime DEFAULT NULL COMMENT '解绑时间',
  `unbindSerial` char(50) NOT NULL DEFAULT '' COMMENT '解绑时的流水号',
  `unbindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '解绑次数',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `game_channel_openid` (`openid`) COMMENT '索引：业务-渠道-openid',
  KEY `channel_uid` (`uid`) COMMENT '索引：渠道-uid'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='渠道用户和游戏角色的绑定关系表';
CREATE TABLE `tb_auth_aqtw_10025553` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增唯一ID',
  `scope` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '授权范围,目前只有0,活动粒度授权',
  `actId` varchar(64) NOT NULL COMMENT '活动id',
  `uid` varchar(64) NOT NULL COMMENT '渠道侧用户ID',
  `openid` varchar(64) NOT NULL COMMENT '游戏账号openid/gopenid',
  `sArea` varchar(8) NOT NULL DEFAULT '' COMMENT '大区',
  `sPlatId` varchar(8) NOT NULL DEFAULT '' COMMENT '平台ID',
  `sPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '小区ID',
  `sRoleId` varchar(64) NOT NULL DEFAULT '' COMMENT '角色ID',
  `srcPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '出生服小区ID，用于转区',
  `sAmsNewRoleId` varchar(80) NOT NULL DEFAULT '' COMMENT '唯一角色ID，用于转区',
  `sExtend` varchar(512) NOT NULL DEFAULT '' COMMENT '绑定的扩展信息，JSON格式',
  `data` text COMMENT '绑定数据，JSON 格式',
  `bindStatus` tinyint(3) unsigned NOT NULL COMMENT '绑定状态：1-已绑定，2-已解绑',
  `bindTime` datetime NOT NULL COMMENT '绑定时间',
  `bindSerial` char(50) NOT NULL COMMENT '绑定时的流水号',
  `bindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '绑定次数',
  `bindFrom` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定来源',
  `bindPhone` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定的手机号',
  `unbindTime` datetime DEFAULT NULL COMMENT '解绑时间',
  `unbindSerial` char(50) NOT NULL DEFAULT '' COMMENT '解绑时的流水号',
  `unbindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '解绑次数',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `game_channel_openid` (`openid`) COMMENT '索引：业务-渠道-openid',
  KEY `channel_uid` (`uid`) COMMENT '索引：渠道-uid'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='渠道用户和游戏角色的绑定关系表';
CREATE TABLE `tb_auth_aqtw_10059313` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增唯一ID',
  `scope` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '授权范围,目前只有0,活动粒度授权',
  `actId` varchar(64) NOT NULL COMMENT '活动id',
  `uid` varchar(64) NOT NULL COMMENT '渠道侧用户ID',
  `openid` varchar(64) NOT NULL COMMENT '游戏账号openid/gopenid',
  `sArea` varchar(8) NOT NULL DEFAULT '' COMMENT '大区',
  `sPlatId` varchar(8) NOT NULL DEFAULT '' COMMENT '平台ID',
  `sPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '小区ID',
  `sRoleId` varchar(64) NOT NULL DEFAULT '' COMMENT '角色ID',
  `srcPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '出生服小区ID，用于转区',
  `sAmsNewRoleId` varchar(80) NOT NULL DEFAULT '' COMMENT '唯一角色ID，用于转区',
  `sExtend` varchar(512) NOT NULL DEFAULT '' COMMENT '绑定的扩展信息，JSON格式',
  `data` text COMMENT '绑定数据，JSON 格式',
  `bindStatus` tinyint(3) unsigned NOT NULL COMMENT '绑定状态：1-已绑定，2-已解绑',
  `bindTime` datetime NOT NULL COMMENT '绑定时间',
  `bindSerial` char(50) NOT NULL COMMENT '绑定时的流水号',
  `bindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '绑定次数',
  `bindFrom` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定来源',
  `bindPhone` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定的手机号',
  `unbindTime` datetime DEFAULT NULL COMMENT '解绑时间',
  `unbindSerial` char(50) NOT NULL DEFAULT '' COMMENT '解绑时的流水号',
  `unbindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '解绑次数',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `game_channel_openid` (`openid`) COMMENT '索引：业务-渠道-openid',
  KEY `channel_uid` (`uid`) COMMENT '索引：渠道-uid'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='渠道用户和游戏角色的绑定关系表';
CREATE TABLE `tb_auth_aqtw_20000001` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增唯一ID',
  `scope` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '授权范围,目前只有0,活动粒度授权',
  `actId` varchar(64) NOT NULL COMMENT '活动id',
  `uid` varchar(64) NOT NULL COMMENT '渠道侧用户ID',
  `openid` varchar(64) NOT NULL COMMENT '游戏账号openid/gopenid',
  `sArea` varchar(8) NOT NULL DEFAULT '' COMMENT '大区',
  `sPlatId` varchar(8) NOT NULL DEFAULT '' COMMENT '平台ID',
  `sPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '小区ID',
  `sRoleId` varchar(64) NOT NULL DEFAULT '' COMMENT '角色ID',
  `srcPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '出生服小区ID，用于转区',
  `sAmsNewRoleId` varchar(80) NOT NULL DEFAULT '' COMMENT '唯一角色ID，用于转区',
  `sExtend` varchar(512) NOT NULL DEFAULT '' COMMENT '绑定的扩展信息，JSON格式',
  `data` text COMMENT '绑定数据，JSON 格式',
  `bindStatus` tinyint(3) unsigned NOT NULL COMMENT '绑定状态：1-已绑定，2-已解绑',
  `bindTime` datetime NOT NULL COMMENT '绑定时间',
  `bindSerial` char(50) NOT NULL COMMENT '绑定时的流水号',
  `bindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '绑定次数',
  `bindFrom` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定来源',
  `bindPhone` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定的手机号',
  `unbindTime` datetime DEFAULT NULL COMMENT '解绑时间',
  `unbindSerial` char(50) NOT NULL DEFAULT '' COMMENT '解绑时的流水号',
  `unbindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '解绑次数',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `game_channel_openid` (`openid`) COMMENT '索引：业务-渠道-openid',
  KEY `channel_uid` (`uid`) COMMENT '索引：渠道-uid'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='渠道用户和游戏角色的绑定关系表';
CREATE TABLE `tb_auth_aqtw_10004231` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增唯一ID',
  `scope` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '授权范围,目前只有0,活动粒度授权',
  `actId` varchar(64) NOT NULL COMMENT '活动id',
  `uid` varchar(64) NOT NULL COMMENT '渠道侧用户ID',
  `openid` varchar(64) NOT NULL COMMENT '游戏账号openid/gopenid',
  `sArea` varchar(8) NOT NULL DEFAULT '' COMMENT '大区',
  `sPlatId` varchar(8) NOT NULL DEFAULT '' COMMENT '平台ID',
  `sPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '小区ID',
  `sRoleId` varchar(64) NOT NULL DEFAULT '' COMMENT '角色ID',
  `srcPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '出生服小区ID，用于转区',
  `sAmsNewRoleId` varchar(80) NOT NULL DEFAULT '' COMMENT '唯一角色ID，用于转区',
  `sExtend` varchar(512) NOT NULL DEFAULT '' COMMENT '绑定的扩展信息，JSON格式',
  `data` text COMMENT '绑定数据，JSON 格式',
  `bindStatus` tinyint(3) unsigned NOT NULL COMMENT '绑定状态：1-已绑定，2-已解绑',
  `bindTime` datetime NOT NULL COMMENT '绑定时间',
  `bindSerial` char(50) NOT NULL COMMENT '绑定时的流水号',
  `bindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '绑定次数',
  `bindFrom` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定来源',
  `bindPhone` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定的手机号',
  `unbindTime` datetime DEFAULT NULL COMMENT '解绑时间',
  `unbindSerial` char(50) NOT NULL DEFAULT '' COMMENT '解绑时的流水号',
  `unbindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '解绑次数',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `game_channel_openid` (`openid`) COMMENT '索引：业务-渠道-openid',
  KEY `channel_uid` (`uid`) COMMENT '索引：渠道-uid'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='渠道用户和游戏角色的绑定关系表';
CREATE TABLE `tb_auth_aqtw_10022592` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增唯一ID',
  `scope` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '授权范围,目前只有0,活动粒度授权',
  `actId` varchar(64) NOT NULL COMMENT '活动id',
  `uid` varchar(64) NOT NULL COMMENT '渠道侧用户ID',
  `openid` varchar(64) NOT NULL COMMENT '游戏账号openid/gopenid',
  `sArea` varchar(8) NOT NULL DEFAULT '' COMMENT '大区',
  `sPlatId` varchar(8) NOT NULL DEFAULT '' COMMENT '平台ID',
  `sPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '小区ID',
  `sRoleId` varchar(64) NOT NULL DEFAULT '' COMMENT '角色ID',
  `srcPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '出生服小区ID，用于转区',
  `sAmsNewRoleId` varchar(80) NOT NULL DEFAULT '' COMMENT '唯一角色ID，用于转区',
  `sExtend` varchar(512) NOT NULL DEFAULT '' COMMENT '绑定的扩展信息，JSON格式',
  `data` text COMMENT '绑定数据，JSON 格式',
  `bindStatus` tinyint(3) unsigned NOT NULL COMMENT '绑定状态：1-已绑定，2-已解绑',
  `bindTime` datetime NOT NULL COMMENT '绑定时间',
  `bindSerial` char(50) NOT NULL COMMENT '绑定时的流水号',
  `bindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '绑定次数',
  `bindFrom` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定来源',
  `bindPhone` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定的手机号',
  `unbindTime` datetime DEFAULT NULL COMMENT '解绑时间',
  `unbindSerial` char(50) NOT NULL DEFAULT '' COMMENT '解绑时的流水号',
  `unbindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '解绑次数',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `game_channel_openid` (`openid`) COMMENT '索引：业务-渠道-openid',
  KEY `channel_uid` (`uid`) COMMENT '索引：渠道-uid'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='渠道用户和游戏角色的绑定关系表';
CREATE TABLE `tb_auth_aqtw_10059312` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增唯一ID',
  `scope` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '授权范围,目前只有0,活动粒度授权',
  `actId` varchar(64) NOT NULL COMMENT '活动id',
  `uid` varchar(64) NOT NULL COMMENT '渠道侧用户ID',
  `openid` varchar(64) NOT NULL COMMENT '游戏账号openid/gopenid',
  `sArea` varchar(8) NOT NULL DEFAULT '' COMMENT '大区',
  `sPlatId` varchar(8) NOT NULL DEFAULT '' COMMENT '平台ID',
  `sPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '小区ID',
  `sRoleId` varchar(64) NOT NULL DEFAULT '' COMMENT '角色ID',
  `srcPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '出生服小区ID，用于转区',
  `sAmsNewRoleId` varchar(80) NOT NULL DEFAULT '' COMMENT '唯一角色ID，用于转区',
  `sExtend` varchar(512) NOT NULL DEFAULT '' COMMENT '绑定的扩展信息，JSON格式',
  `data` text COMMENT '绑定数据，JSON 格式',
  `bindStatus` tinyint(3) unsigned NOT NULL COMMENT '绑定状态：1-已绑定，2-已解绑',
  `bindTime` datetime NOT NULL COMMENT '绑定时间',
  `bindSerial` char(50) NOT NULL COMMENT '绑定时的流水号',
  `bindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '绑定次数',
  `bindFrom` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定来源',
  `bindPhone` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定的手机号',
  `unbindTime` datetime DEFAULT NULL COMMENT '解绑时间',
  `unbindSerial` char(50) NOT NULL DEFAULT '' COMMENT '解绑时的流水号',
  `unbindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '解绑次数',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `game_channel_openid` (`openid`) COMMENT '索引：业务-渠道-openid',
  KEY `channel_uid` (`uid`) COMMENT '索引：渠道-uid'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='渠道用户和游戏角色的绑定关系表';
CREATE TABLE `tb_auth_aqtw_10628090` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增唯一ID',
  `scope` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '授权范围,目前只有0,活动粒度授权',
  `actId` varchar(64) NOT NULL COMMENT '活动id',
  `uid` varchar(64) NOT NULL COMMENT '渠道侧用户ID',
  `openid` varchar(64) NOT NULL COMMENT '游戏账号openid/gopenid',
  `sArea` varchar(8) NOT NULL DEFAULT '' COMMENT '大区',
  `sPlatId` varchar(8) NOT NULL DEFAULT '' COMMENT '平台ID',
  `sPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '小区ID',
  `sRoleId` varchar(64) NOT NULL DEFAULT '' COMMENT '角色ID',
  `srcPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '出生服小区ID，用于转区',
  `sAmsNewRoleId` varchar(80) NOT NULL DEFAULT '' COMMENT '唯一角色ID，用于转区',
  `sExtend` varchar(512) NOT NULL DEFAULT '' COMMENT '绑定的扩展信息，JSON格式',
  `data` text COMMENT '绑定数据，JSON 格式',
  `bindStatus` tinyint(3) unsigned NOT NULL COMMENT '绑定状态：1-已绑定，2-已解绑',
  `bindTime` datetime NOT NULL COMMENT '绑定时间',
  `bindSerial` char(50) NOT NULL COMMENT '绑定时的流水号',
  `bindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '绑定次数',
  `bindFrom` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定来源',
  `bindPhone` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定的手机号',
  `unbindTime` datetime DEFAULT NULL COMMENT '解绑时间',
  `unbindSerial` char(50) NOT NULL DEFAULT '' COMMENT '解绑时的流水号',
  `unbindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '解绑次数',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `game_channel_openid` (`openid`) COMMENT '索引：业务-渠道-openid',
  KEY `channel_uid` (`uid`) COMMENT '索引：渠道-uid'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='渠道用户和游戏角色的绑定关系表';
CREATE TABLE `tb_auth_aqtw_10003392` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增唯一ID',
  `scope` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '授权范围,目前只有0,活动粒度授权',
  `actId` varchar(64) NOT NULL COMMENT '活动id',
  `uid` varchar(64) NOT NULL COMMENT '渠道侧用户ID',
  `openid` varchar(64) NOT NULL COMMENT '游戏账号openid/gopenid',
  `sArea` varchar(8) NOT NULL DEFAULT '' COMMENT '大区',
  `sPlatId` varchar(8) NOT NULL DEFAULT '' COMMENT '平台ID',
  `sPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '小区ID',
  `sRoleId` varchar(64) NOT NULL DEFAULT '' COMMENT '角色ID',
  `srcPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '出生服小区ID，用于转区',
  `sAmsNewRoleId` varchar(80) NOT NULL DEFAULT '' COMMENT '唯一角色ID，用于转区',
  `sExtend` varchar(512) NOT NULL DEFAULT '' COMMENT '绑定的扩展信息，JSON格式',
  `data` text COMMENT '绑定数据，JSON 格式',
  `bindStatus` tinyint(3) unsigned NOT NULL COMMENT '绑定状态：1-已绑定，2-已解绑',
  `bindTime` datetime NOT NULL COMMENT '绑定时间',
  `bindSerial` char(50) NOT NULL COMMENT '绑定时的流水号',
  `bindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '绑定次数',
  `bindFrom` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定来源',
  `bindPhone` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定的手机号',
  `unbindTime` datetime DEFAULT NULL COMMENT '解绑时间',
  `unbindSerial` char(50) NOT NULL DEFAULT '' COMMENT '解绑时的流水号',
  `unbindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '解绑次数',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `game_channel_openid` (`openid`) COMMENT '索引：业务-渠道-openid',
  KEY `channel_uid` (`uid`) COMMENT '索引：渠道-uid'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='渠道用户和游戏角色的绑定关系表';
CREATE TABLE `tb_auth_aqtw_10003898` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增唯一ID',
  `scope` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '授权范围,目前只有0,活动粒度授权',
  `actId` varchar(64) NOT NULL COMMENT '活动id',
  `uid` varchar(64) NOT NULL COMMENT '渠道侧用户ID',
  `openid` varchar(64) NOT NULL COMMENT '游戏账号openid/gopenid',
  `sArea` varchar(8) NOT NULL DEFAULT '' COMMENT '大区',
  `sPlatId` varchar(8) NOT NULL DEFAULT '' COMMENT '平台ID',
  `sPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '小区ID',
  `sRoleId` varchar(64) NOT NULL DEFAULT '' COMMENT '角色ID',
  `srcPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '出生服小区ID，用于转区',
  `sAmsNewRoleId` varchar(80) NOT NULL DEFAULT '' COMMENT '唯一角色ID，用于转区',
  `sExtend` varchar(512) NOT NULL DEFAULT '' COMMENT '绑定的扩展信息，JSON格式',
  `data` text COMMENT '绑定数据，JSON 格式',
  `bindStatus` tinyint(3) unsigned NOT NULL COMMENT '绑定状态：1-已绑定，2-已解绑',
  `bindTime` datetime NOT NULL COMMENT '绑定时间',
  `bindSerial` char(50) NOT NULL COMMENT '绑定时的流水号',
  `bindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '绑定次数',
  `bindFrom` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定来源',
  `bindPhone` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定的手机号',
  `unbindTime` datetime DEFAULT NULL COMMENT '解绑时间',
  `unbindSerial` char(50) NOT NULL DEFAULT '' COMMENT '解绑时的流水号',
  `unbindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '解绑次数',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `game_channel_openid` (`openid`) COMMENT '索引：业务-渠道-openid',
  KEY `channel_uid` (`uid`) COMMENT '索引：渠道-uid'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='渠道用户和游戏角色的绑定关系表';
CREATE TABLE `tb_auth_aqtw_10017385` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增唯一ID',
  `scope` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '授权范围,目前只有0,活动粒度授权',
  `actId` varchar(64) NOT NULL COMMENT '活动id',
  `uid` varchar(64) NOT NULL COMMENT '渠道侧用户ID',
  `openid` varchar(64) NOT NULL COMMENT '游戏账号openid/gopenid',
  `sArea` varchar(8) NOT NULL DEFAULT '' COMMENT '大区',
  `sPlatId` varchar(8) NOT NULL DEFAULT '' COMMENT '平台ID',
  `sPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '小区ID',
  `sRoleId` varchar(64) NOT NULL DEFAULT '' COMMENT '角色ID',
  `srcPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '出生服小区ID，用于转区',
  `sAmsNewRoleId` varchar(80) NOT NULL DEFAULT '' COMMENT '唯一角色ID，用于转区',
  `sExtend` varchar(512) NOT NULL DEFAULT '' COMMENT '绑定的扩展信息，JSON格式',
  `data` text COMMENT '绑定数据，JSON 格式',
  `bindStatus` tinyint(3) unsigned NOT NULL COMMENT '绑定状态：1-已绑定，2-已解绑',
  `bindTime` datetime NOT NULL COMMENT '绑定时间',
  `bindSerial` char(50) NOT NULL COMMENT '绑定时的流水号',
  `bindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '绑定次数',
  `bindFrom` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定来源',
  `bindPhone` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定的手机号',
  `unbindTime` datetime DEFAULT NULL COMMENT '解绑时间',
  `unbindSerial` char(50) NOT NULL DEFAULT '' COMMENT '解绑时的流水号',
  `unbindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '解绑次数',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `game_channel_openid` (`openid`) COMMENT '索引：业务-渠道-openid',
  KEY `channel_uid` (`uid`) COMMENT '索引：渠道-uid'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='渠道用户和游戏角色的绑定关系表';
CREATE TABLE `tb_auth_aqtw_10059310` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增唯一ID',
  `scope` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '授权范围,目前只有0,活动粒度授权',
  `actId` varchar(64) NOT NULL COMMENT '活动id',
  `uid` varchar(64) NOT NULL COMMENT '渠道侧用户ID',
  `openid` varchar(64) NOT NULL COMMENT '游戏账号openid/gopenid',
  `sArea` varchar(8) NOT NULL DEFAULT '' COMMENT '大区',
  `sPlatId` varchar(8) NOT NULL DEFAULT '' COMMENT '平台ID',
  `sPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '小区ID',
  `sRoleId` varchar(64) NOT NULL DEFAULT '' COMMENT '角色ID',
  `srcPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '出生服小区ID，用于转区',
  `sAmsNewRoleId` varchar(80) NOT NULL DEFAULT '' COMMENT '唯一角色ID，用于转区',
  `sExtend` varchar(512) NOT NULL DEFAULT '' COMMENT '绑定的扩展信息，JSON格式',
  `data` text COMMENT '绑定数据，JSON 格式',
  `bindStatus` tinyint(3) unsigned NOT NULL COMMENT '绑定状态：1-已绑定，2-已解绑',
  `bindTime` datetime NOT NULL COMMENT '绑定时间',
  `bindSerial` char(50) NOT NULL COMMENT '绑定时的流水号',
  `bindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '绑定次数',
  `bindFrom` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定来源',
  `bindPhone` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定的手机号',
  `unbindTime` datetime DEFAULT NULL COMMENT '解绑时间',
  `unbindSerial` char(50) NOT NULL DEFAULT '' COMMENT '解绑时的流水号',
  `unbindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '解绑次数',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `game_channel_openid` (`openid`) COMMENT '索引：业务-渠道-openid',
  KEY `channel_uid` (`uid`) COMMENT '索引：渠道-uid'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='渠道用户和游戏角色的绑定关系表';
CREATE TABLE `tb_auth_aqtw_10059311` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增唯一ID',
  `scope` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '授权范围,目前只有0,活动粒度授权',
  `actId` varchar(64) NOT NULL COMMENT '活动id',
  `uid` varchar(64) NOT NULL COMMENT '渠道侧用户ID',
  `openid` varchar(64) NOT NULL COMMENT '游戏账号openid/gopenid',
  `sArea` varchar(8) NOT NULL DEFAULT '' COMMENT '大区',
  `sPlatId` varchar(8) NOT NULL DEFAULT '' COMMENT '平台ID',
  `sPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '小区ID',
  `sRoleId` varchar(64) NOT NULL DEFAULT '' COMMENT '角色ID',
  `srcPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '出生服小区ID，用于转区',
  `sAmsNewRoleId` varchar(80) NOT NULL DEFAULT '' COMMENT '唯一角色ID，用于转区',
  `sExtend` varchar(512) NOT NULL DEFAULT '' COMMENT '绑定的扩展信息，JSON格式',
  `data` text COMMENT '绑定数据，JSON 格式',
  `bindStatus` tinyint(3) unsigned NOT NULL COMMENT '绑定状态：1-已绑定，2-已解绑',
  `bindTime` datetime NOT NULL COMMENT '绑定时间',
  `bindSerial` char(50) NOT NULL COMMENT '绑定时的流水号',
  `bindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '绑定次数',
  `bindFrom` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定来源',
  `bindPhone` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定的手机号',
  `unbindTime` datetime DEFAULT NULL COMMENT '解绑时间',
  `unbindSerial` char(50) NOT NULL DEFAULT '' COMMENT '解绑时的流水号',
  `unbindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '解绑次数',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `game_channel_openid` (`openid`) COMMENT '索引：业务-渠道-openid',
  KEY `channel_uid` (`uid`) COMMENT '索引：渠道-uid'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='渠道用户和游戏角色的绑定关系表';
CREATE TABLE `tb_auth_aqtw_10497811` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增唯一ID',
  `scope` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '授权范围,目前只有0,活动粒度授权',
  `actId` varchar(64) NOT NULL COMMENT '活动id',
  `uid` varchar(64) NOT NULL COMMENT '渠道侧用户ID',
  `openid` varchar(64) NOT NULL COMMENT '游戏账号openid/gopenid',
  `sArea` varchar(8) NOT NULL DEFAULT '' COMMENT '大区',
  `sPlatId` varchar(8) NOT NULL DEFAULT '' COMMENT '平台ID',
  `sPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '小区ID',
  `sRoleId` varchar(64) NOT NULL DEFAULT '' COMMENT '角色ID',
  `srcPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '出生服小区ID，用于转区',
  `sAmsNewRoleId` varchar(80) NOT NULL DEFAULT '' COMMENT '唯一角色ID，用于转区',
  `sExtend` varchar(512) NOT NULL DEFAULT '' COMMENT '绑定的扩展信息，JSON格式',
  `data` text COMMENT '绑定数据，JSON 格式',
  `bindStatus` tinyint(3) unsigned NOT NULL COMMENT '绑定状态：1-已绑定，2-已解绑',
  `bindTime` datetime NOT NULL COMMENT '绑定时间',
  `bindSerial` char(50) NOT NULL COMMENT '绑定时的流水号',
  `bindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '绑定次数',
  `bindFrom` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定来源',
  `bindPhone` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定的手机号',
  `unbindTime` datetime DEFAULT NULL COMMENT '解绑时间',
  `unbindSerial` char(50) NOT NULL DEFAULT '' COMMENT '解绑时的流水号',
  `unbindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '解绑次数',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `game_channel_openid` (`openid`) COMMENT '索引：业务-渠道-openid',
  KEY `channel_uid` (`uid`) COMMENT '索引：渠道-uid'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='渠道用户和游戏角色的绑定关系表';
CREATE TABLE `tb_auth_aqtw_10018084` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增唯一ID',
  `scope` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '授权范围,目前只有0,活动粒度授权',
  `actId` varchar(64) NOT NULL COMMENT '活动id',
  `uid` varchar(64) NOT NULL COMMENT '渠道侧用户ID',
  `openid` varchar(64) NOT NULL COMMENT '游戏账号openid/gopenid',
  `sArea` varchar(8) NOT NULL DEFAULT '' COMMENT '大区',
  `sPlatId` varchar(8) NOT NULL DEFAULT '' COMMENT '平台ID',
  `sPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '小区ID',
  `sRoleId` varchar(64) NOT NULL DEFAULT '' COMMENT '角色ID',
  `srcPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '出生服小区ID，用于转区',
  `sAmsNewRoleId` varchar(80) NOT NULL DEFAULT '' COMMENT '唯一角色ID，用于转区',
  `sExtend` varchar(512) NOT NULL DEFAULT '' COMMENT '绑定的扩展信息，JSON格式',
  `data` text COMMENT '绑定数据，JSON 格式',
  `bindStatus` tinyint(3) unsigned NOT NULL COMMENT '绑定状态：1-已绑定，2-已解绑',
  `bindTime` datetime NOT NULL COMMENT '绑定时间',
  `bindSerial` char(50) NOT NULL COMMENT '绑定时的流水号',
  `bindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '绑定次数',
  `bindFrom` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定来源',
  `bindPhone` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定的手机号',
  `unbindTime` datetime DEFAULT NULL COMMENT '解绑时间',
  `unbindSerial` char(50) NOT NULL DEFAULT '' COMMENT '解绑时的流水号',
  `unbindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '解绑次数',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `game_channel_openid` (`openid`) COMMENT '索引：业务-渠道-openid',
  KEY `channel_uid` (`uid`) COMMENT '索引：渠道-uid'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='渠道用户和游戏角色的绑定关系表';
CREATE TABLE `tb_auth_aqtw_10029304` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增唯一ID',
  `scope` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '授权范围,目前只有0,活动粒度授权',
  `actId` varchar(64) NOT NULL COMMENT '活动id',
  `uid` varchar(64) NOT NULL COMMENT '渠道侧用户ID',
  `openid` varchar(64) NOT NULL COMMENT '游戏账号openid/gopenid',
  `sArea` varchar(8) NOT NULL DEFAULT '' COMMENT '大区',
  `sPlatId` varchar(8) NOT NULL DEFAULT '' COMMENT '平台ID',
  `sPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '小区ID',
  `sRoleId` varchar(64) NOT NULL DEFAULT '' COMMENT '角色ID',
  `srcPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '出生服小区ID，用于转区',
  `sAmsNewRoleId` varchar(80) NOT NULL DEFAULT '' COMMENT '唯一角色ID，用于转区',
  `sExtend` varchar(512) NOT NULL DEFAULT '' COMMENT '绑定的扩展信息，JSON格式',
  `data` text COMMENT '绑定数据，JSON 格式',
  `bindStatus` tinyint(3) unsigned NOT NULL COMMENT '绑定状态：1-已绑定，2-已解绑',
  `bindTime` datetime NOT NULL COMMENT '绑定时间',
  `bindSerial` char(50) NOT NULL COMMENT '绑定时的流水号',
  `bindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '绑定次数',
  `bindFrom` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定来源',
  `bindPhone` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定的手机号',
  `unbindTime` datetime DEFAULT NULL COMMENT '解绑时间',
  `unbindSerial` char(50) NOT NULL DEFAULT '' COMMENT '解绑时的流水号',
  `unbindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '解绑次数',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `game_channel_openid` (`openid`) COMMENT '索引：业务-渠道-openid',
  KEY `channel_uid` (`uid`) COMMENT '索引：渠道-uid'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='渠道用户和游戏角色的绑定关系表';
CREATE TABLE `tb_auth_aqtw_10029992` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增唯一ID',
  `scope` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '授权范围,目前只有0,活动粒度授权',
  `actId` varchar(64) NOT NULL COMMENT '活动id',
  `uid` varchar(64) NOT NULL COMMENT '渠道侧用户ID',
  `openid` varchar(64) NOT NULL COMMENT '游戏账号openid/gopenid',
  `sArea` varchar(8) NOT NULL DEFAULT '' COMMENT '大区',
  `sPlatId` varchar(8) NOT NULL DEFAULT '' COMMENT '平台ID',
  `sPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '小区ID',
  `sRoleId` varchar(64) NOT NULL DEFAULT '' COMMENT '角色ID',
  `srcPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '出生服小区ID，用于转区',
  `sAmsNewRoleId` varchar(80) NOT NULL DEFAULT '' COMMENT '唯一角色ID，用于转区',
  `sExtend` varchar(512) NOT NULL DEFAULT '' COMMENT '绑定的扩展信息，JSON格式',
  `data` text COMMENT '绑定数据，JSON 格式',
  `bindStatus` tinyint(3) unsigned NOT NULL COMMENT '绑定状态：1-已绑定，2-已解绑',
  `bindTime` datetime NOT NULL COMMENT '绑定时间',
  `bindSerial` char(50) NOT NULL COMMENT '绑定时的流水号',
  `bindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '绑定次数',
  `bindFrom` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定来源',
  `bindPhone` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定的手机号',
  `unbindTime` datetime DEFAULT NULL COMMENT '解绑时间',
  `unbindSerial` char(50) NOT NULL DEFAULT '' COMMENT '解绑时的流水号',
  `unbindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '解绑次数',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `game_channel_openid` (`openid`) COMMENT '索引：业务-渠道-openid',
  KEY `channel_uid` (`uid`) COMMENT '索引：渠道-uid'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='渠道用户和游戏角色的绑定关系表';
CREATE TABLE `tb_auth_aqtw_10484106` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增唯一ID',
  `scope` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '授权范围,目前只有0,活动粒度授权',
  `actId` varchar(64) NOT NULL COMMENT '活动id',
  `uid` varchar(64) NOT NULL COMMENT '渠道侧用户ID',
  `openid` varchar(64) NOT NULL COMMENT '游戏账号openid/gopenid',
  `sArea` varchar(8) NOT NULL DEFAULT '' COMMENT '大区',
  `sPlatId` varchar(8) NOT NULL DEFAULT '' COMMENT '平台ID',
  `sPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '小区ID',
  `sRoleId` varchar(64) NOT NULL DEFAULT '' COMMENT '角色ID',
  `srcPartition` varchar(8) NOT NULL DEFAULT '' COMMENT '出生服小区ID，用于转区',
  `sAmsNewRoleId` varchar(80) NOT NULL DEFAULT '' COMMENT '唯一角色ID，用于转区',
  `sExtend` varchar(512) NOT NULL DEFAULT '' COMMENT '绑定的扩展信息，JSON格式',
  `data` text COMMENT '绑定数据，JSON 格式',
  `bindStatus` tinyint(3) unsigned NOT NULL COMMENT '绑定状态：1-已绑定，2-已解绑',
  `bindTime` datetime NOT NULL COMMENT '绑定时间',
  `bindSerial` char(50) NOT NULL COMMENT '绑定时的流水号',
  `bindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '绑定次数',
  `bindFrom` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定来源',
  `bindPhone` varchar(32) NOT NULL DEFAULT '' COMMENT '绑定的手机号',
  `unbindTime` datetime DEFAULT NULL COMMENT '解绑时间',
  `unbindSerial` char(50) NOT NULL DEFAULT '' COMMENT '解绑时的流水号',
  `unbindCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '解绑次数',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `game_channel_openid` (`openid`) COMMENT '索引：业务-渠道-openid',
  KEY `channel_uid` (`uid`) COMMENT '索引：渠道-uid'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='渠道用户和游戏角色的绑定关系表';
